In [12]:
import numpy as np


In [13]:
# A cell is a group of inputs, weights and a bias
inputs = [1.2,5.3,6.1]
weight = [3.1,5.2,2.3]
bias = 3
output = sum([inputs[x]*weight[x] for x in range(3)])+bias
print(output)

48.309999999999995


In [14]:
# A layer of cells can be defined by the weights and biases of each node, the input is the same for the full layer
weights = [[1.5,-2.3,2.5],
           [2.6,3.5,-1.7],
           [-1.7,4.3,-2.4],
           [-2.4,1.2,-1.7]]
biases = [2,6,3,1]
outputs = [sum([inputs[j]*weights[i][j] for j in range(3)])+biases[i] for i in range(4)]
print(outputs)

[6.859999999999999, 17.300000000000004, 9.110000000000001, -5.89]


In [15]:
# Use np to speed up the work with vectorization
outputs = np.dot(weights,inputs)+biases
print(outputs)

[ 6.86 17.3   9.11 -5.89]


In [16]:
# Batch fitting with multiples inputs
inputs = [[1.2,5.3,6.1],
          [3.3,5.2,4.1],
          [5.2,2.5,3.2],
          [6.2,4.3,3.2],
          [2.1,5.6,9.4]]
# Th weights need to be transposed
outputs = np.dot(inputs,np.array(weights).T)+biases
print(outputs)

[[  6.86  17.3    9.11  -5.89]
 [  5.24  25.81   9.91  -7.65]
 [ 12.05  22.83  -2.77 -13.92]
 [  9.41  31.73   3.27 -14.16]
 [ 15.77  15.08   0.95 -13.3 ]]
