In [3]:
import numpy as np
import matplotlib as mtp
from Layer import Dense
from Activation import ReLU, SoftMax
from NeuralNetwork import NeuralNetwork
from Loss import CategoricalCrossEntropy

X = np.random.randn(100,10)
nn = NeuralNetwork()
nn.addLayer(Dense(10,16), ReLU())
nn.addLayer(Dense(16,4), SoftMax())

nn.forward(X)
nn.calculateLoss(CategoricalCrossEntropy())

print(nn.loss)
print(nn.output)

[[0.23948493 0.25990528 0.24019903 0.26041076]
 [0.19531455 0.25425735 0.28615093 0.26427717]
 [0.19848801 0.287843   0.24985576 0.26381324]
 [0.2067586  0.2644218  0.27974467 0.24907493]
 [0.17869388 0.26650395 0.28442794 0.27037423]
 [0.19195549 0.28002422 0.27644636 0.25157392]
 [0.22637059 0.25493341 0.28804736 0.23064864]
 [0.2236819  0.25283598 0.25275653 0.27072558]
 [0.2186546  0.26874729 0.24190778 0.27069033]
 [0.24750201 0.26011795 0.24133733 0.25104271]
 [0.21889111 0.27568673 0.231848   0.27357416]
 [0.24412113 0.25826782 0.24669414 0.25091691]
 [0.23217924 0.27588315 0.26520174 0.22673587]
 [0.24520799 0.2533501  0.25080483 0.25063708]
 [0.24133429 0.26238014 0.25668443 0.23960114]
 [0.23937027 0.2651783  0.2331134  0.26233803]
 [0.22752794 0.26676542 0.25920408 0.24650256]
 [0.22009446 0.27276221 0.26574715 0.24139618]
 [0.22682712 0.25082366 0.23799671 0.2843525 ]
 [0.1952229  0.29159215 0.25301837 0.26016658]
 [0.23951929 0.25166333 0.2567752  0.25204218]
 [0.23513675 